apiVersion: v1
kind: Service
metadata:
  name: mysql      
spec:
  selector:                  
    deploymentconfig: mysql
  ports:
  - nodePort: 0
    port: 3306              
    protocol: TCP
    targetPort: 3306
